version: '3'

services:
  django:
    container_name: djangoapp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=be_great
      - POSTGRES_USER=be_great
      - POSTGRES_PASSWORD=be_great
    ports:
      - "5432:5432"
